meta_product_name: "MyCryptoWallet - Digital Assets Portfolio"
meta_title: "MyCryptoWallet - Add good stress to your life!"
meta_description: "MyCryptoWallet is the most efficient way to manage different portfolios, to know your earnings, to receive alerts. MyCryptoWallet gives access to one of the largest selections of Coins, allowing you to follow over 20 assets with more to come..."
meta_image: "investisment.jpg" # should exist in `app/assets/images/`
twitter_account: "@binance"   # required for Twitter Cards
