development:
  stripe:
    private_key: xxxx
    public_key: yyyy
    signing_secret: zzzz
  braintree:
    private_key: xxxx
    public_key: yyyy
    merchant_id: aaaa
    environment: sandbox
  paddle:
    vendor_id: xxxx
    vendor_auth_code: yyyy
    public_key_base64: MII...==
    environment: sandbox
